_BASE_: "Base-RCNN-FPN_convnext.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "See Instructions"
  MASK_ON: True
  BACKBONE:
    NAME: "build_convnext_fpn_backbone"
    FREEZE_AT: 0
  CONVNEXT:
    DEPTHS: [3, 3, 27, 3]
    DIMS: [96, 192, 384, 768]
    DROP_PATH_RATE: 0.2
    LAYER_SCALE_INIT_VALUE: 1e-6
    OUT_FEATURES: [0, 1, 2, 3]
  FPN:
    IN_FEATURES: [0, 1, 2, 3]
    NORM: SyncBN
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    NORM: SyncBN
INPUT:
  FORMAT: "RGB"
SOLVER:
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_RATE: 0.95
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
# SOLVER:
#   WEIGHT_DECAY: 0.0001
#   AMP:
#     ENABLED: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
TEST:
  PRECISE_BN:
    ENABLED: True